package com.automationpractice.tests.locators;

import java.util.concurrent.TimeUnit;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.Test;

import io.github.bonigarcia.wdm.WebDriverManager;

public class LocaltorsDemo {
	
	
	@Test
	public void attr() {
		WebDriverManager.chromedriver().setup();
		WebDriver webdriver = new ChromeDriver();
		webdriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
		webdriver.get("http://automationpractice.com/index.php?controller=authentication&back=my-account");
		
		WebElement create_acct_btn = webdriver.findElement(By.id("SubmitCreate"));
		
		System.out.println(create_acct_btn);
		
		create_acct_btn.click();
		
		
		String attVal = create_acct_btn.getAttribute("class");
		System.out.println(attVal);
		
		
		
		
	}
	
	
	@Test
	public void problemOfAutoGeneratedCssSelectorAndXpath() {
		
		WebDriverManager.chromedriver().setup();
		WebDriver webdriver = new ChromeDriver();
		webdriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
		webdriver.get("file:///F:/Time%20And%20Training/Demo%20Folder/HtmlTableDemo/table1.html");
		
		String perc = webdriver.findElement(By.cssSelector(".own")).getText();
		System.out.println(perc);
	}
	
	
	@Test
	public void usingCssSelectors() {
		WebDriverManager.chromedriver().setup();
		WebDriver webdriver = new ChromeDriver();
		webdriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
		
		
	}
	
	@Test
	public void usingId() {
		WebDriverManager.chromedriver().setup();
		WebDriver webdriver = new ChromeDriver();
		webdriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
		
		webdriver.get("http://automationpractice.com/");
		webdriver.findElement(By.id("search_query_top")).sendKeys("testing locator");
		
		
	}
	
	
	@Test
	public void usingClass() {
		WebDriverManager.chromedriver().setup();
		WebDriver webdriver = new ChromeDriver();
		webdriver.manage().timeouts().implicitlyWait(15, TimeUnit.SECONDS);
		
		
		webdriver.get("http://automationpractice.com/");
		webdriver.findElement(By.className("login")).click();
		
		
	}
}
